(defun create-matrix (rows cols init-fn)
  (let ((matrix '()))
    (dotimes (i rows)
      (push (mapcar init-fn (make-list cols :initial-element 0)) matrix))
    (nreverse matrix)))

(defun matrix-dimensions (matrix)
  (let ((rows (length matrix))
        (cols (length (first matrix))))
    (values rows cols)))

(defun matrix-mul (a b)
  (multiple-value-bind (a-rows a-cols) (matrix-dimensions a)
    (multiple-value-bind (b-rows b-cols) (matrix-dimensions b)
      (when (/= a-cols b-rows)
        (error "Incompatible matrix dimensions for multiplication"))
      (let ((result (create-matrix a-rows b-cols (lambda () 0))))
        (dotimes (i a-rows)
          (dotimes (j b-cols)
            (let ((sum 0))
              (dotimes (k a-cols)
                (setf sum (+ sum (* (nth i a) (nth k (nth j b))))))
              (setf (nth i (nth j result)) sum))))
        result)))))

(defun transpose-matrix (matrix)
  (let ((rows (length matrix))
        (cols (length (first matrix))))
    (create-matrix cols rows (lambda (idx)
                               (nth idx (mapcar #'first matrix))))))


(defun apply-function-to-matrix (matrix func)
  (mapcar (lambda (row)
            (mapcar func row))
          matrix))

(defun initialize-weights (rows cols)
  (create-matrix rows cols (lambda () (- (random 2.0) 1.0))))

(defun zeros-matrix (rows cols)
  (create-matrix rows cols (lambda () 0)))

(defun neural-layer (input-dim output-dim)
  (let ((weights (initialize-weights output-dim input-dim))
        (biases (initialize-weights output-dim 1)))
    (list :weights weights :biases biases)))

(defun forward-pass (layer input)
  (let* ((weights (getf layer :weights))
         (biases (getf layer :biases))
         (z (matrix-mul weights input))
         (z-bias (mapcar* #'+ z (transpose-matrix biases))))
         (a (apply-function-to-matrix z-bias (lambda (x) (max 0 x)))))
    a))

(defun relu (matrix)
  (apply-function-to-matrix matrix (lambda (x) (max 0 x))))

(defun relu-derivative (matrix)
  (apply-function-to-matrix matrix (lambda (x) (if (> x 0) 1 0))))

(defun softmax (matrix)
  (mapcar (lambda (row)
            (let ((max-val (apply #'max row))
                  (exps '()))
              (setf exps (mapcar (lambda (x) (exp (- x max-val))) row))
              (let ((sum-exps (apply #'+ exps)))
                (mapcar (lambda (e) (/ e sum-exps)) exps))))
          )
          matrix))

(defun compute-loss (predictions targets)
  (let ((m (length predictions)))
    (apply #'+
           (mapcar* (lambda (pred targ)
                      (- (apply #'+ (mapcar* (lambda (p t) (* t (log p))) pred targ))
                         (* (apply #'+ (mapcar* (lambda (p) (* p p)) pred)) 0))))
                    predictions targets))))

(defun backpropagate (layer input output target learning-rate)
  (let ((weights (getf layer :weights))
        (biases (getf layer :biases))
        (m (length input)))
    (let ((delta (mapcar* (lambda (o t) (- o t))
                          output target))
          (dA (if (null (cdr input))
                   input
                   input)))
      (let ((dZ (mapcar* (lambda (d a) (* d (if (> a 0) 1 0)))
                          delta (transpose-matrix activation))))
        (let ((dW (matrix-mul (transpose-matrix dZ) input))
              (dB (transpose-matrix dZ)))
          (setf (getf layer :weights)
                (mapcar* (lambda (w row)
                           (mapcar* (lambda (w_ dw_) (- w_ (* learning-rate (/ dw_ m)))) row))
                           weights))
                )
          (setf (getf layer :biases)
                (mapcar* (lambda (b db)
                           (- b (* learning-rate (/ db m))))
                         biases dB))
          layer)))))

(defun train-neural-network (layers input-targets epochs learning-rate)
  (dotimes (epoch epochs)
    (let ((total-loss 0))
      (dolist (pair input-targets)
        (let ((input (car pair))
              (target (cadr pair)))
          (let ((activation input))
            (dolist (layer layers)
              (setf activation (forward-pass layer activation)))
            (let ((predictions activation))
              (setf total-loss (+ total-loss (compute-loss predictions target)))
              (let ((grad (mapcar (lambda (p t) (- p t)) predictions target)))
                (setf activation input)
                (dolist (layer layers)
                  (backpropagate layer activation predictions target learning-rate)
                  (setf activation (forward-pass layer activation))))))))))))
  layers)

(defun initialize-layer (input-dim output-dim)
  (neural-layer input-dim output-dim))