#lang racket

(define (vector3 x y z) (list x y z))
(define (vec-x v) (first v))
(define (vec-y v) (second v))
(define (vec-z v) (third v))
(define (vec-add v1 v2) (map + v1 v2))
(define (vec-sub v1 v2) (map - v1 v2))
(define (vec-scale v s) (map (λ (x) (* x s)) v))
(define (vec-dot v1 v2) (+ (* (vec-x v1) (vec-x v2))
                            (* (vec-y v1) (vec-y v2))
                            (* (vec-z v1) (vec-z v2))))
(define (vec-cross v1 v2)
  (vector3
   (- (* (vec-y v1) (vec-z v2)) (* (vec-z v1) (vec-y v2)))
   (- (* (vec-z v1) (vec-x v2)) (* (vec-x v1) (vec-z v2)))
   (- (* (vec-x v1) (vec-y v2)) (* (vec-y v1) (vec-x v2)))))
(define (vec-length v)
  (sqrt (vec-dot v v)))
(define (normalize v)
  (let ((len (vec-length v))) (if (> len 0) (vec-scale v (/ 1.0 len)) v)))
(define (reflect v n)
  (vec-sub v (vec-scale n (* 2 (vec-dot v n)))))
(define (refract v n eta)
  (let* ((cosi (max (- (vec-dot v n)) 0) -1))
         (cost (sqrt (- 1.0 (* eta eta (- 1.0 (expt cosi 2)))))))
         (r1 (vec-scale v eta))
         (r2 (vec-scale n (+ cosi (* eta cost))))
         (refracted (vec-add r1 r2)))
    (normalize refracted)))
(define (schlick cos ior)
  (let ((r0 (/ (- 1.0 ior) (+ 1.0 ior))))
    (let ((r0 (expt r0 2)))
      (+ r0 (* (- 1 r0) (expt (- 1 cos) 5)))))))
(define (hash-vector v)
  (hash 'x (vec-x v) 'y (vec-y v) 'z (vec-z v)))
(define (mix a b t)
  (vec-add (vec-scale a (- 1 t)) (vec-scale b t)))
(define (clamp x min max)
  (max min (min x max)))
(define (rgb-to-color r g b)
  (list (clamp r 0 1) (clamp g 0 1) (clamp b 0 1)))
(define (color-scale c s)
  (list (clamp (* (first c) s) 0 1)
        (clamp (* (second c) s) 0 1)
        (clamp (* (third c) s) 0 1)))
(define (color-add c1 c2)
  (list (clamp (+ (first c1) (first c2)) 0 1)
        (clamp (+ (second c1) (second c2)) 0 1)
        (clamp (+ (third c1) (third c2)) 0 1)))
)
(define (sample-noise x y seed)
  (modulo (+ (hash-vector (vector3 x y 0)) seed) 1))
(define (perlin-noise x y seed)
  (let* ((xi (floor x))
         (yi (floor y))
         (xf (- x xi))
         (yf (- y yi))
         (u (fade xf))
         (v (fade yf))
         (n00 (grad (hash-vector (vector3 xi yi 0)) xf yf))
         (n01 (grad (hash-vector (vector3 xi (+ yi 1) 0)) xf (- 1.0 yf)))
         (n10 (grad (hash-vector (vector3 (+ xi 1) yi 0)) (- 1.0 xf) yf))
         (n11 (grad (hash-vector (vector3 (+ xi 1) (+ yi 1) 0)) (- 1.0 xf) (- 1.0 yf))))
     (lerp v (lerp u n00 n10) (lerp u n01 n11))))
)
(define (fade t) (let ((t t)) (+ (* t t t) (* 6 t* t) (* 15 t* t t* t t))))
(define (lerp t a b) (+ (* a (- 1 t)) (* b t)))
(define (grad hash x y)
  (let ((h (hash %)))
    (if (even? h)
        (+ (* (vec-x (vector3 1 0 0)) x) (* (vec-y (vector3 0 1 0)) y))
        (+ (* (vec-x (vector3 0 1 0)) x) (* (vec-y (vector3 1 0 0)) y)))))
)
(define (generate-normal pos sampleSeed)
  (normalize (vector3 (perlin-noise (+ (vec-x pos) 1) (vec-y pos) sampleSeed)
                      (perlin-noise (vec-x pos) (+ (vec-y pos) 1) sampleSeed)
                      0)))
)
(define (compute-shading point normal viewDir material lightPosition lightColor)
  (let* ((diffuse-intensity (max 0 (vec-dot normal (normalize (vector3 (- (vec-x lightPosition))
                                                                          (- (vec-y lightPosition))
                                                                          (- (vec-z lightPosition))))))))
         (diffuse (color-scale lightColor diffuse-intensity))
         (specular-coefficient 0.5)
         (reflectDir (reflect (normalize (vec-sub (vector3 0 0 0) (normalize (vector3 (- (vec-x lightPosition))
                                                                                     (- (vec-y lightPosition))
                                                                                     (- (vec-z lightPosition))))))) normal))
         (specAngle (max 0 (vec-dot viewDir reflectDir)))
         (specular (color-scale lightColor (expt specAngle 32)))
         (ambient (color-scale lightColor 0.1))
         (color (color-add (color-add diffuse specular) ambient)))
    (list (vector3 (first color) (second color) (third color)))))
(define (shade-point point normal viewDir material lightPosition lightColor seed)
  (let ((normal (generate-normal point seed))
        (viewDir (normalize viewDir))
        (lightDir (normalize (vector3 (- (vec-x lightPosition))
                                        (- (vec-y lightPosition))
                                        (- (vec-z lightPosition)))))))
    (compute-shading point normal viewDir material lightPosition lightColor)))
(define (simulate-shading points normals viewDirs materials lights seed)
  (map (λ (pt idx)
         (let ((n (list-ref normals idx))
               (v (list-ref viewDirs idx))
               (mat (list-ref materials idx))
               (light (list-ref lights 0))
               (lightPos (vector3 10 10 10))
               (lightCol (vector3 1 1 1)))
           (shade-point pt n v mat lightPos lightCol seed)))
       points (range (length points))))
)
(define points (list (vector3 0 0 0) (vector3 1 0 0) (vector3 0 1 0) (vector3 -1 0 0) (vector3 0 -1 0)))
(define normals (list 
                 (generate-normal (vector3 0 0 0) 42)
                 (generate-normal (vector3 1 0 0) 42)
                 (generate-normal (vector3 0 1 0) 42)
                 (generate-normal (vector3 -1 0 0) 42)
                 (generate-normal (vector3 0 -1 0) 42)))
(define viewDirs (list (vector3 0 0 1) (vector3 0 0 1) (vector3 0 0 1) (vector3 0 0 1) (vector3 0 0 1)))
(define materials (list 
                   '((color . (1 0 0)) reflectivity . 0.5)
                   '((color . (0 1 0)) reflectivity . 0.4)
                   '((color . (0 0 1)) reflectivity . 0.6)
                   '((color . (1 1 0)) reflectivity . 0.3)
                   '((color . (0 1 1)) reflectivity . 0.7)))
(define lights (list (vector3 10 10 10)))
(define seed 12345)
(define shaded-results (simulate-shading points normals viewDirs materials lights seed))