(defparameter *gravity* 9.81)
(defparameter *dt* 0.016)
(defparameter *collision-damping* 0.8)
(defparameter *air-resistance* 0.99)
(defparameter *world-size* (list 100 100 100))
(defparameter *particles* (list))
(defparameter *forces* (list))
(defparameter *bodies* (list))
(defparameter *time* 0.0)

(defun create-particle (mass position velocity)
  (list :mass mass
        :position position
        :velocity velocity
        :acceleration (list 0 0 0)
        :forces (list)))

(defun apply-force (body force)
  (push force (plist-get body :forces)))

(defun update-forces ()
  (dolist (body *bodies*)
    (setf (plist-get body :acceleration)
          (mapcar (lambda (f)
                    (/ f (plist-get body :mass)))
                  (plist-get body :forces)))
    (setf (plist-get body :forces) '()))))

(defun integrate (body)
  (let* ((pos (plist-get body :position))
         (vel (plist-get body :velocity))
         (acc (plist-get body :acceleration))
         (new-vel (mapcar #'+ vel (mapcar #'* acc (list *dt* *dt* *dt*))))
         (new-pos (mapcar #'+ pos (mapcar #'* new-vel *dt*))))
    (setf (plist-get body :velocity) new-vel)
    (setf (plist-get body :position) new-pos)))

(defun handle-collisions (body)
  (let* ((pos (plist-get body :position))
         (vel (plist-get body :velocity))
         (mass (plist-get body :mass))
         (x (nth 0 pos))
         (y (nth 1 pos))
         (z (nth 2 pos))
         (vx (nth 0 vel))
         (vy (nth 1 vel))
         (vz (nth 2 vel))
         (size *world-size*))
    (when (< x 0)
      (setf (nth 0 (plist-get body :velocity)) (* vx -collision-damping))
      (setf (nth 0 (plist-get body :position)) 0))
    (when (> x (nth 0 size))
      (setf (nth 0 (plist-get body :velocity)) (* vx -collision-damping))
      (setf (nth 0 (plist-get body :position)) (nth 0 size)))
    (when (< y 0)
      (setf (nth 1 (plist-get body :velocity)) (* vy -collision-damping))
      (setf (nth 1 (plist-get body :position)) 0))
    (when (> y (nth 1 size))
      (setf (nth 1 (plist-get body :velocity)) (* vy -collision-damping))
      (setf (nth 1 (plist-get body :position)) (nth 1 size)))
    (when (< z 0)
      (setf (nth 2 (plist-get body :velocity)) (* vz -collision-damping))
      (setf (nth 2 (plist-get body :position)) 0))
    (when (> z (nth 2 size))
      (setf (nth 2 (plist-get body :velocity)) (* vz -collision-damping))
      (setf (nth 2 (plist-get body :position)) (nth 2 size)))))

(defun apply-air-resistance (body)
  (let ((vel (plist-get body :velocity)))
    (setf (plist-get body :velocity)
          (mapcar (lambda (v) (* v *air-resistance*)) vel))))

(defun update-body (body)
  (update-forces)
  (integrate body)
  (apply-air-resistance body)
  (handle-collisions body))

(defun simulate-step ()
  (dolist (body *bodies*)
    (update-body body))
  (setf *time* (+ *time* *dt*)))

(defun add-particle (mass position velocity)
  (push (create-particle mass position velocity) *bodies*))

(defun apply-gravity ()
  (dolist (body *bodies*)
    (apply-force body (list (* (plist-get body :mass) -gravity*)))))

(defun initialize-simulation ()
  (push (create-particle 1.0 (list 50 50 50) (list 0 0 0)) *bodies*)
  (push (create-particle 2.0 (list 20 20 20) (list 10 15 5)) *bodies*))

(defun run-simulation (steps)
  (initialize-simulation)
  (dotimes (i steps)
    (apply-gravity)
    (simulate-step)))

(defun get-bodies ()
  *bodies*)

(defun set-bodies (bodies)
  (setf *bodies* bodies))